# Generated by Django 4.2.16 on 2024-12-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/')),
                ('tagline', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('Pet_listing', models.URLField(default='http://example.com')),
            ],
        ),
    ]
