# Generated by Django 4.2.16 on 2024-12-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petShop', '0002_remove_hero_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('flaticon-blind', 'Dog Walking Icon'), ('flaticon-dog-eating', 'Pet Daycare Icon'), ('flaticon-grooming', 'Pet Grooming Icon')], max_length=50)),
                ('link', models.URLField()),
            ],
        ),
    ]
