# Generated by Django 4.2.16 on 2024-12-20 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petShop', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Why Choose Us?', max_length=255)),
                ('background_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('flaticon-stethoscope', 'Stethoscope Icon'), ('flaticon-customer-service', 'Customer Service Icon'), ('flaticon-emergency-call', 'Emergency Call Icon'), ('flaticon-veterinarian', 'Veterinarian Icon')], max_length=50)),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='petShop.whychooseus')),
            ],
        ),
    ]
