# Generated by Django 4.2.16 on 2024-12-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petShop', '0007_pet_date_added_alter_pet_age_alter_pet_breed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
    ]
