# Generated by Django 4.2.16 on 2024-12-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petShop', '0009_remove_faq_answer_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veteran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='staff_photos/')),
                ('description', models.TextField()),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('google_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
